### ISSUE TITLE
Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by redVi** [amitpatra/gatsby-remark-highlights#1]
Hi! When the code looks like the following, the plugin throws an exception.

```
~~~
# ~/.gemrc
gem: --no-rdoc --no-ri
~~~
```

This is due to the `lang = lang.toLowerCase();` string in the `index.js` file because `lang` is `null` in this case.

Maybe it's worth checking if the variable is empty?

**Comment by amitpatra** [comment]
Oops!! never really thought about that case. Going to fix it.

**Comment by amitpatra** [comment]
@redVi  v1.1.4 fix this issue.
