### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by azdanov** [amitpatra/gatsby-remark-highlights#17]
Is this repo still maintained?

**Comment by amitpatra** [comment]
Well actually I am thinking about V2 with some more features and pull requests are always welcomed, so it is maintained in some sense and sorry for late reply.

**Comment by azdanov** [comment]
Thanks for your time. The plugin is really good. I've been using it for a while and 0 issues.

Will be happy to send any relevant PR's to this project.

**Comment by amitpatra** [comment]
Thanks for your kind words :) I will probably update the docs later this week. Again thank you.

**Comment by azdanov** [comment]
I'm baffled that your plugin isn't more popular. It offer __much__ better results for code syntax, via atom's grammar.

Closing this issue, since it's been resolved.
