### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by RobertMyles** [amitpatra/gatsby-remark-highlights#22]
Hi, 
Would you be able to provide a complete example of how to use the package? I'm unsure how to go about compiling a theme from Atom and then using it with gatsby. 

Thanks!

**Comment by amitpatra** [comment]
Hi, sorry for the late reply. Yes I will try to document the steps for doing that as soon as possible. You can use https://github.com/MoOx/atom-syntax-theme-to-highlights-css to transform an Atom theme to CSS ready to be used by code highlighted with atom/highlights.

**Comment by RobertMyles** [comment]
Great, thanks! I'll close this so.
